### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#104]
Reset password should be hidden for oauth2

<img width="1115" alt="Screenshot 2023-01-29 at 4 29 39 PM" src="https://user-images.githubusercontent.com/24913433/215333289-730b3fb3-fa6c-4713-9101-02aae0e2ecdc.png">

**Comment by navid-farjad** [comment]
Please recheck if we show Reset password only on account with "email_verified" true
