### ISSUE TITLE
Page refresh takes limit

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#107]
![FBB9BB75-7910-4886-A756-EFEB65E61578](https://user-images.githubusercontent.com/24913433/218101088-10cec808-a682-4479-9099-021998000a74.jpeg)
refreshing the page does something to the limits and we charge user's limits twice

we have to charge limit ONLY if user clicks on button CHECK

![23933D10-F4ED-420B-B5A4-2D5B1AC0D20C](https://user-images.githubusercontent.com/24913433/218101190-b8590287-8f77-4d05-93cd-09e574a99d62.jpeg)
![90F74FBC-BB13-4080-BBF1-D1DD9764D1F0](https://user-images.githubusercontent.com/24913433/218101200-7d3e9902-b4df-4cf4-926c-a1c91ac51670.jpeg)

every time I refresh page now, I'm getting charged + I see a lot of duplication in wallet checks fro today

![E64C1C66-0C98-4139-8CE1-3788E1AEF79F](https://user-images.githubusercontent.com/24913433/218101294-7fd977fa-d6d9-4977-b805-5eabf4af066d.jpeg)

**Comment by navid-farjad** [comment]
Please add check id in url after you get the result so refresh will not create new check
