### ISSUE TITLE
add csv and pdf

### ISSUE THREAD

**Issue by navid-farjad** [Exeltive-Group-Ltd/block#13]

**Comment by alexeyltd** [comment]
PDF ->

[EyeBlock – Crypto Wallet Screening report.docx](https://github.com/Exeltive-Group-Ltd/EyeBlock/files/10393565/EyeBlock.Crypto.Wallet.Screening.report.docx)

**Comment by alexeyltd** [comment]
csv -> 

just data from the page(what we have on the page into csv
