### ISSUE TITLE
Source of funds

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#21]
{{risk_base_url}}/v1/risk/score/details?chain=btc&address=bc1q4upe70649lt647t93fc6vwzncdkmj204aq7pew

```
{
    "case_id": "1828b330-5104-4fad-8a63-ce5e7fdf3f54",
    "request_datetime": "2023-01-11T17:07:00Z",
    "response_datetime": "2023-01-11T17:07:00Z",
    "chain": "btc",
    "address": "bc1q4upe70649lt647t93fc6vwzncdkmj204aq7pew",
    "name": "Investment in terror",
    "category_name": "Scams & Investment Frauds",
    "risk": 100,
    "details": {
        "own_categories": [
            {
                "address": "bc1q4upe70649lt647t93fc6vwzncdkmj204aq7pew",
                "name": "Investment in terror",
                "category_name": "Scams & Investment Frauds",
                "risk": 100
            }
        ],
        "source_of_funds_categories": []
    }
}
```

prod link -> https://app.eyeblock.io/crypto-wallet-screening/wallets/b832be59-8c90-46f5-95dc-917d3c61d644?address=bc1q4upe70649lt647t93fc6vwzncdkmj204aq7pew&chain=null&check_id=ef9856bd-4e37-47c0-bfd3-5cb24bc5edf7

<img width="1089" alt="Screenshot 2023-01-11 at 7 08 09 PM" src="https://user-images.githubusercontent.com/24913433/211870941-f359921b-37f9-4bb5-942b-fa98e24d7a8b.png">

**Comment by navid-farjad** [comment]
https://github.com/Exeltive-Group-Ltd/block/issues/28
