### ISSUE TITLE
Sentry errors

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#26]
https://o104379.ingest.sentry.io/api/5495040/envelope/?sentry_key=5be7bb2583284b3ca5221379bc5517b8&sentry_version=7&sentry_client=sentry.javascript.react%2F7.28.1

"event submission rejected with_reason: Cors"

<img width="568" alt="Screenshot 2023-01-11 at 7 38 38 PM" src="https://user-images.githubusercontent.com/24913433/211878340-e1534ddf-d960-42d9-b9d4-a7b3cb3e6241.png">

**Comment by dumbasPL** [comment]
For anyone that found this from search, this sentry key: `5be7bb2583284b3ca5221379bc5517b8` belongs to the chrome extension [Revolut Shopper](https://chrome.google.com/webstore/detail/revolut-shopper/hdlehfdjcalidklijenibmpcdgjfmafn?hl=en)
