### ISSUE TITLE
NEO transaction history

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#68]
https://eyeblock-front-git-dev-eyeblock-team.vercel.app/crypto-wallet-screening/wallets/61cda988-19ab-4d67-9676-589b77c7ccf5?address=AH1fYcEUYa4TX4q7EpjXw4yjUUf4D3WxDN&chain=NEO

there're no transaction history + exception pop up :(

<img width="1136" alt="Screenshot 2023-01-17 at 6 50 48 PM" src="https://user-images.githubusercontent.com/24913433/212961195-00852c56-a01c-4973-bcf5-a18e90e6089b.png">

**Comment by alexeyltd** [comment]
https://eyeblock-front-git-dev-eyeblock-team.vercel.app/crypto-wallet-screening/wallets/61cda988-19ab-4d67-9676-589b77c7ccf5?address=AH1fYcEUYa4TX4q7EpjXw4yjUUf4D3WxDN&chain=nNEO&check_id=3ea340a0-5540-4c35-8504-6049bd63779c

**Comment by navid-farjad** [comment]
![image](https://user-images.githubusercontent.com/30972233/213926767-9103a870-a6ae-457f-b20f-e52ff2b01475.png)

please check undefined in api request for conversion
