### ISSUE TITLE
ETH wallet(wrong data)

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#71]
https://blockchair.com/ethereum/address/0xda9dfa130df4de4673b89022ee50ff26f6ea73cf

https://eyeblock-front-git-dev-eyeblock-team.vercel.app/crypto-wallet-screening/wallets/5f439217-626e-4457-bf90-d63d41cc5136?address=0xda9dfa130df4de4673b89022ee50ff26f6ea73cf&chain=ETH

**Comment by navid-farjad** [comment]
0xda9dfa130df4de4673b89022ee50ff26f6ea73cf
eth
