### ISSUE TITLE
We show result too fast

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#75]
We should show **correct** result after backend sends data to fronted otherwise users sees NaN/0 which is wrong

<img width="1104" alt="Screenshot 2023-01-20 at 9 36 13 AM" src="https://user-images.githubusercontent.com/24913433/213641871-3c7dd7f4-7cf1-4b1f-be77-352ad8b879e9.png">

**Comment by alexeyltd** [comment]
@navid-farjad I don't this it's in v2, that's what we need to do now since we need to show correct result...

**Comment by navid-farjad** [comment]
@alexeyltd if its non means sync is not done and we dont have balance from blockmate. in v2 you need to show some loader that we are waiting to sync
