### ISSUE TITLE
Failed Change Password Request

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#81]
After clicking on reset password, I don't get any email or what should happen?

**Comment by navid-farjad** [comment]
@alexeyltd can you please test this

**Comment by alexeyltd** [comment]
I verified domain in Amazon SES -> 
<img width="1075" alt="Screenshot 2023-01-28 at 10 48 12 AM" src="https://user-images.githubusercontent.com/24913433/215256614-e818524c-ea48-46b6-a696-97914d6a91e4.png">

**Comment by alexeyltd** [comment]
I don't get email, that's why, link -> https://manage.auth0.com/dashboard/us/dev-jjzahydp1bcdlaqr/logs/90020230128090419939888802355565283522190097833900638226?page=1

<img width="1075" alt="Screenshot 2023-01-28 at 11 05 54 AM" src="https://user-images.githubusercontent.com/24913433/215257400-2bcc52fb-10c5-444d-88b2-d29140af4a3b.png">

**Comment by alexeyltd** [comment]
Now emails are through Amazon SES

<img width="1100" alt="Screenshot 2023-01-28 at 11 09 03 AM" src="https://user-images.githubusercontent.com/24913433/215257552-236d17cf-e963-4c63-b3a5-6d56c0a0b34c.png">

**Comment by alexeyltd** [comment]
But -> Auth0 says -> User does not exist.

**Comment by navid-farjad** [comment]
@alexeyltd have you ever registered with this email?! or you logged in with google and trying to change password?

**Comment by navid-farjad** [comment]
this should not happen for new user after deploy
