### ISSUE TITLE
Registration with github

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#82]
Idk why, but after allowing github registration I'm redirected to the url -> https://app.eyeblock.io/verification

<img width="1440" alt="Screenshot 2023-01-22 at 3 51 24 PM" src="https://user-images.githubusercontent.com/24913433/213919340-78f1607c-a503-4a1f-881f-315a4953212c.png">

**Comment by alexeyltd** [comment]
<img width="981" alt="Screenshot 2023-01-26 at 7 42 11 PM"@navid-farjad src="https://user-images.githubusercontent.com/24913433/214909480-5828d719-e19e-4134-8f09-64252d5a3e57.png">


@navid-farjad

**Comment by navid-farjad** [comment]
@alexeyltd image you uploaded is not visible!

**Comment by alexeyltd** [comment]
@navid-farjad do you have access to this? https://github.com/organizations/Exeltive-Group-Ltd/settings/apps/eyeblock

**Comment by alexeyltd** [comment]
<img width="1002" alt="Screenshot 2023-01-28 at 11 13 59 AM" src="https://user-images.githubusercontent.com/24913433/215257753-235d61b1-ea98-4ad6-b307-6af6317e0e41.png">

**Comment by alexeyltd** [comment]
<img width="703" alt="Screenshot 2023-01-28 at 11 14 52 AM" src="https://user-images.githubusercontent.com/24913433/215257846-5e4424d6-7a5d-4574-9101-95af170a7f40.png">

**Comment by navid-farjad** [comment]
![Uploading image.png…]()

**Comment by navid-farjad** [comment]
@alexeyltd i dont have access
