### ISSUE TITLE
Connect google data studio

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#85]

**Comment by alexeyltd** [comment]
<img width="1432" alt="Screenshot 2023-01-26 at 7 45 00 P@navid-farjad  src="https://user-images.githubusercontent.com/24913433/214910057-e2d122ee-e8e1-422a-a1bb-9d835e452a96.png">

@navid-farjad what should I do?

**Comment by navid-farjad** [comment]
@alexeyltd  I need a gsuit account credentials for this!

**Comment by alexeyltd** [comment]
@navid-farjad let's use noreply account for this?
