### ISSUE TITLE
Connect JS live chat

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#86]

**Comment by alexeyltd** [comment]
I will provide js code, let's delete live chat section in the menu, since live chat will pop up always

**Comment by navid-farjad** [comment]
please send me the code

**Comment by alexeyltd** [comment]
@navid-farjad 
`<script src="//code.tidio.co/a6hl52jitqg6t4cslkohrhi8w3uwopol.js" async></script>`

**Comment by navid-farjad** [comment]
#frontend please check if you can trigger the chat buy selecting chat on left menu as well for Tidio chat
