### ISSUE TITLE
We don't show loading until we get transitions 

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#89]
link -> https://app.eyeblock.io/crypto-wallet-screening/wallets/1c2ee737-7f93-4c6c-a0a9-e1efce2d8170?address=0x9696f59e4d72e237be84ffd425dcad154bf96976&chain=ETH

I've tried to connect wallets with many transactions in order to test the loading, currently the situation is this:

<img width="1083" alt="Screenshot 2023-01-24 at 10 33 21 AM" src="https://user-images.githubusercontent.com/24913433/214245194-4ef1a7ee-86e4-46fa-af1d-093e4dee1222.png">

I have the balance but risk score 0 and transactions are in loading stage. Our partners were confused because they thought we have already analysed the wallet.

We need to show results after we get all data from blockmate until that time, let's show loading... We discussed it but I don't see this logic on fronted side...

**Comment by navid-farjad** [comment]
NA for score 
"syncing..." for last sync
