### ISSUE TITLE
Can't analyse celo wallets

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#91]
<img width="1440" alt="Screenshot 2023-01-24 at 10 45 34 AM" src="https://user-images.githubusercontent.com/24913433/214247451-69b51ebc-efe3-4758-b557-1b025ab4c40f.png">

**0x045D685D23e8Aa34Dc408a66Fb408f20DC84d785**

**Comment by navid-farjad** [comment]
![image](https://user-images.githubusercontent.com/30972233/214339718-9b95d823-8701-49fd-a5f8-ad7e723a74ed.png)

@alexeyltd this is blockmate issue. it gives timeout
