### ISSUE TITLE
NEO wallets risk score page is strange

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#92]
https://app.eyeblock.io/crypto-wallet-screening/wallets/0952406e-a19f-48b8-aaec-575660094a1a?address=AH1fYcEUYa4TX4q7EpjXw4yjUUf4D3WxDN&chain=NEO

**AH1fYcEUYa4TX4q7EpjXw4yjUUf4D3WxDN**

**Comment by navid-farjad** [comment]
@alexeyltd what is strange here?

**Comment by alexeyltd** [comment]
<img width="1083" alt="Screenshot 2023-01-24 at 6 43 47 PM" src="https://user-images.githubusercontent.com/24913433/214354500-e2ea8ce2-110c-4da6-bbe9-9ac36fb379f9.png">
