### ISSUE TITLE
Can't analize Ripple wallets

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#94]
https://app.eyeblock.io/crypto-wallet-screening/wallets/08e2eb80-226e-4d7d-9f8c-e35cf3918e5d?address=rMLUc76TXkGoMyXTLe7Re6jZwfZuuhGQkb&chain=XRP

**rMLUc76TXkGoMyXTLe7Re6jZwfZuuhGQkb**

**Comment by navid-farjad** [comment]
![image](https://user-images.githubusercontent.com/30972233/214327826-2e0c94b0-b2e0-41d7-8d82-0969a7771f49.png)


sync takes forever
