### ISSUE TITLE
SUSPICIOUS TRANSACTIONS history recipient

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#97]
Empty recipient :) 

<img width="1076" alt="Screenshot 2023-01-25 at 5 29 27 PM" src="https://user-images.githubusercontent.com/24913433/214604689-8259b3dc-3679-4dac-bdb4-d342b85a7cc1.png">

**Comment by alexeyltd** [comment]
link -> https://app.eyeblock.io/crypto-wallet-screening/wallets/ba049564-b4c6-4b75-b54f-8efa759a4571?address=bc1q8prhhlukpjrtu746zjt0drpzjl3zhhyt7frwsv&chain=BTC&check_id=3a51cf02-e0ba-4adc-9f32-e9f7bbd14234

**Comment by alexeyltd** [comment]
link -> https://app.eyeblock.io/crypto-wallet-screening/wallets/106ab13b-5509-4495-b23d-5ad69e3fbc97?address=bc1q4upe70649lt647t93fc6vwzncdkmj204aq7pew&chain=BTC&check_id=4afe4929-ac44-49d2-9c77-69d7bfd16d03

**Comment by alexeyltd** [comment]
<img width="544" alt="Screenshot 2023-01-25 at 7 43 53 PM" src="https://user-images.githubusercontent.com/24913433/214641264-77cbac40-0529-4db4-afbb-af814eff4a42.png">

**Comment by navid-farjad** [comment]
![image](https://user-images.githubusercontent.com/30972233/215262264-c77a717e-f697-4eb1-bc1b-a1bcb5968548.png)
