### ISSUE TITLE
History check bug

### ISSUE THREAD

**Issue by alexeyltd** [Exeltive-Group-Ltd/block#99]
This wallet has history check with different values but we still showing 0.0

https://app.eyeblock.io/crypto-wallet-screening/wallets/b7f3ce21-c121-4385-8315-7bc1df5883cc?address=xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW&chain=SOLANA:XzR7CUMqhDBzbAm4aUNvwhVCxjWGn1KEvqTp3Y8fFCD&check_id=5df99890-a1dd-4251-951c-bcbd16b7bf78

<img width="1440" alt="Screenshot 2023-01-25 at 7 57 30 PM" src="https://user-images.githubusercontent.com/24913433/214644677-bbfad36e-a422-4c36-8849-5d2b7211b64b.png">

**Comment by alexeyltd** [comment]
`{"user":{"uuid":"2abd6b0f-f12d-4a7b-bafa-ffccae15d7a3","account_id":3,"sub":"google-oauth2|102923583883032705738","created_at":"2023-01-25T14:36:27.762Z","updated_at":"2023-01-25T14:36:27.851Z"},"wallet":{"uuid":"b7f3ce21-c121-4385-8315-7bc1df5883cc","wallet_id":"4e613dc0-4668-43e4-9408-21f883d60010","address":"xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW","name":"sol","description":"xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW","verified":false,"created_at":"2023-01-25T17:54:21.363Z","updated_at":"2023-01-25T17:54:21.369Z","key_version":1},"check_history":[{"uuid":"5df99890-a1dd-4251-951c-bcbd16b7bf78","wallet_id":19,"organization_id":5,"checked_at":"2023-01-25T17:55:41.000Z","score":0.0,"currency":"SOL","currency_name":"SOLANA","currency_symbol":"SOL","value":"29.146354517","created_at":"2023-01-25T17:55:42.358Z","updated_at":"2023-01-25T17:55:42.358Z","wallet":{"uuid":"b7f3ce21-c121-4385-8315-7bc1df5883cc","wallet_id":"4e613dc0-4668-43e4-9408-21f883d60010","address":"xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW","name":"sol","description":"xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW","verified":false,"created_at":"2023-01-25T17:54:21.363Z","updated_at":"2023-01-25T17:54:21.369Z","key_version":1}},{"uuid":"ddb02bd4-8cd2-4ad8-97d5-013ca1c9b38c","wallet_id":19,"organization_id":5,"checked_at":"2023-01-25T17:55:16.000Z","score":0.0,"currency":"SOLANA:XzR7CUMqhDBzbAm4aUNvwhVCxjWGn1KEvqTp3Y8fFCD","currency_name":"Scammer Token Beware","currency_symbol":"SCAM","value":"2.0","created_at":"2023-01-25T17:55:17.036Z","updated_at":"2023-01-25T17:55:17.036Z","wallet":{"uuid":"b7f3ce21-c121-4385-8315-7bc1df5883cc","wallet_id":"4e613dc0-4668-43e4-9408-21f883d60010","address":"xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW","name":"sol","description":"xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW","verified":false,"created_at":"2023-01-25T17:54:21.363Z","updated_at":"2023-01-25T17:54:21.369Z","key_version":1}}],"balance":{}}`

**Comment by navid-farjad** [comment]
![image](https://user-images.githubusercontent.com/30972233/215262675-5e00ab80-bf7b-4b34-9c62-bf247dc5535f.png)
i didnt understand the issue here, there are multiple check with 0 score, is it different from blockmate?

**Comment by alexeyltd** [comment]
How is it possible that in your screen currency is different?
